version: '3'
services:
    mysql:
        image: mysql:8
        restart: always
        volumes:
            - ./migration_files/init.sql:/docker-entrypoint-initdb.d/10-init.sql
        env_file:
            - ./config/.env
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u", "user", "-p${MYSQL_PASSWORD}"]
            timeout: 45s
            interval: 10s
            retries: 10
        ports:
            - "3333:3306"
    app:
        build: .
        ports:
            - 3200:3200
        depends_on:
            mysql:
                condition: service_healthy
